### ISSUE TITLE
CSL not showing up correctly

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1061]
Per Juxtapozblis:

The first is CSLs weren't showing up correctly when the GM (me) made attacks. Image on the left shows the DCV of 11 my player had due to assigning 7 CSLs to his DCV. But when I rolled an attack targeted at him, you can see in the screenshot on the right, it says he has DCV of 4 which is his standard DCV.

![image](https://github.com/dmdorman/hero6e-foundryvtt/assets/13549766/fdd5915b-0fac-479b-b9cd-07c846ae9be0)

**Comment by aeauseth** [comment]
I was not able to reproduce this issue.

**Comment by AGreaterMonster** [comment]
Greetings. I'm the one who reported the bug. Let me know what else I can check. The screenshot on the left was my player. The previous round he had assigned his CSLs to defense. The screenshot on the right is me attacking him the next phase with the agent but you can see in parens it is assigning him his base DCV of 4 instead of 11. I don't know if it matters, but I self-host and there was no lag on the map for the players but do you think there could be some sort of lag in updating the content? My ethernet speed is good, though, usually runs around 900MBPs.

**Comment by aeauseth** [comment]
CSL only last until your next phase.  I was able to reproduce this when a player and the foe both have the same speed (3 for example), but the foe has a higher DEX.  The player on segment 4 assigns the CSLs, then on segment 8 the CSLs expire, but the foe goes first.

I need to brainstorm a bit to find a solution.

**Comment by AGreaterMonster** [comment]
> CSL only last until your next phase. I was able to reproduce this when a player and the foe both have the same speed (3 for example), but the foe has a higher DEX. The player on segment 4 assigns the CSLs, then on segment 8 the CSLs expire, but the foe goes first.
> 
> I need to brainstorm a bit to find a solution.

Ah, interesting. That could be it. Also of note, it expires to the GM because it shows up to enemies with CSLs unassigned, but the Player still sees it where he last set it on his sheet and the Stats are still boosted. As they should be.

**Comment by aeauseth** [comment]
We now expire Active Effects on token's phase, not on token's segment.

**Comment by AGreaterMonster** [comment]
Fantastic. You guys rock.
