### ISSUE TITLE
Area Effect options for attack

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#41]
An attack power might have an area effect Advantage, This should be reflected in the damage dialogue. For example, if attack X has the 8m cone area effect, if it hits (DCV 3 for area effects), an 8m cone should be placed or at least an option for that. See the Savage Worlds power dialogues for examples.

**Comment by dmdorman** [comment]
Added in v2.1.3-alpha. I need to add this to the documentation still, but after rolling an attack with some AoE specified you should be able to click the pinkish/purplish AoE tag to spawn the measured template. Unfortunately its a bit frustrating to work with because you can easily rotate it without right clicking on the template and setting it from there.
