### ISSUE TITLE
Autofire attack option

### ISSUE THREAD

**Issue by techogre** [dmdorman/hero6e-foundryvtt#43]
Attack options need to have the Autofire option.

**Comment by aeauseth** [comment]
There are two options for AUTOFIRE.

1. AUTOFIRE AGAINST A SINGLE TARGET
2. AUTOFIRE AGAINST MULTIPLE TARGETS

I'm thinking a dropdown or something in the initial attack roll to specify SINGLE or MULTIPLE targets.  You could select the targets (shift-t) and automate the -1 OCV and maximum hexes.

I don't see this used very often because target(s) get to apply defense for each hit.  Most games limit Active Points so a single attack is generally more effective vs equal foes.  I've seen it used effectively with penetrating and with mooks.
